### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by Velidan87** [DavidEGx/bga-carcassonne-reviewer#4]
Hi! I'm writing because I don't understand how to use these Javascript.
I tried to follow your setup instructions and copy the script to a new page in my Chrome browser, but I got error code 413, as happened also to other users.
My guess is that I am doing something wrong... Could you please explain to me step by step what I need to do to get the tool working?
I really thank you in advance for your kind support!

**Comment by DavidEGx** [comment]
Hi,

Instructions doesn't tell you to open a new page and visit the _thing_.
You just need to add a new bookmark with the _thing_.

1. Open Chrome

2. Display the Bookmarks Bar:
If your bookmarks bar isn't already visible, you can display it by:

    Pressing Ctrl+Shift+B (on Windows/Linux) or Cmd+Shift+B (on Mac).
    Or, clicking on the three dots (⋮) at the top right corner of the browser to open the Chrome menu, hovering over "Bookmarks", and selecting "Show bookmarks bar".

3. Add a New Bookmark:

    Right-click on the bookmarks bar.
    Choose "Add page..." from the dropdown menu.

    Enter Bookmarklet Details:

        Name: Give your bookmarklet a descriptive name.
        URL: Paste the javascript://wholething

----
or same thing using the bookmark manager:

1. Open Chrome

2. Access the Bookmark Manager:

    Click on the three dots (⋮) at the top right corner of the browser to open the Chrome menu.
    Hover over "Bookmarks" and then click "Bookmark manager." Alternatively, you can press Ctrl+Shift+O (on Windows/Linux) or Cmd+Shift+O (on Mac).

3. Add a New Bookmark:
    In the Bookmark manager:

        Click on the three dots (⋮) at the top right corner.
        Select "Add new bookmark."

4. Enter Bookmarklet Details:

    Name: Give your bookmarklet a descriptive name.
    URL: Paste the javascript://wholething

    Choose the Folder:
    You can save the bookmarklet in any folder. If you want it to be accessible from the bookmarks bar, select the "Bookmarks bar" folder.



----

Hope that works

**Comment by Velidan87** [comment]
Now I got it, you are number 1, thank you so much!!!
